apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  annotations:
    cloud.google.com/load-balancer-type: "external"
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80         # External exposure port (used by LoadBalancer)
      targetPort: 8080 # Target port from the container in your deployment
