#apiVersion: v1
#kind: Service
#metadata:
  #name: myapp-service
  #annotations:
 #   cloud.google.com/load-balancer-type: "external" # Use this for an external LoadBalancer in GCP
#spec:
  #type: LoadBalancer
  #selector:
   # app: myapp # This matches the "app" label on the pods from your Deployment
  #ports:
    #- protocol: TCP
      #port: 80 # The port users access via the LoadBalancer
      #targetPort: 8080 # The containerPort from your Deployment
