name: 'gke-gcloud-auth-plugin'
description: 'gke-gcloud-auth-plugin'
runs:
  using: 'composite'
  steps:
    # Read the current version from the VERSION file
      - name: retrieving version
        shell: bash
        run: |
          # Create the keyring directory
            sudo mkdir -p /usr/share/keyrings

            # Import the correct public key from Google's GPG repository to the keyrings directory
            curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null

            # Add the Google Cloud SDK repository, explicitly referencing the keyring for verification
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

            # Update the package cache and install the gke-gcloud-auth-plugin
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Configure environment to use GKE plugin
        shell: bash
        run: |
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True