name: 'docker login'
description: 'docker login to jfrog artifactory'
inputs:
  jfrog_url:
    description: "jfrog_url"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Docker login to Jfrod artifactory
      shell: bash
      run: |
        docker login -u "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}" ${{ inputs.jfrog_url }}