name: Build and Deploy to JFrog Artifactory

on:
  workflow_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up JDK
      - name: Set Up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Build and Test
      - name: Build and Test
        run: |
          mvn clean package --settings settings.xml \
            -Dartifactory.username=${{ secrets.USERNAME }} \
            -Dartifactory.password=${{ secrets.PASSWORD }}

      # Step 4: Deploy Artifacts to JFrog Artifactory
      - name: Deploy to JFrog Artifactory
        run: |
          mvn deploy --settings settings.xml \
            -Dartifactory.username=${{ secrets.USERNAME }} \
            -Dartifactory.password=${{ secrets.PASSWORD }}
