name: pulling image
on: 
  workflow_dispatch:
    inputs:
      repopath:
        description: "repo name"
        default: "dockertest-docker"
        required: true
      appname:
        description: "app name"
        default: "test"
        required: true
env:
  repopath: ${{ inputs.repopath }}
  appname: ${{ inputs.appname }}
  jfrog_url: "artifactory987.jfrog.io"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: retriving the version
        run: |
          version=$(cat VERSION)
          echo "version=$version" >> $GITHUB_ENV
          echo "version is: ${{ env.version }}"
      - name: Docker login to Jfrod artifactory
        run: |
          docker login -u "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}" ${{ env.jfrog_url }}
      - name: Build and push docker image
        run: |
          docker run artifactory987.jfrog.io/dockertest-docker/test:${{ env.version }}
